name: Release
# only trigger on pull request closed events
on:
  push:
    tags:
      - '*'
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - name: Cache musl cross-compilation toolchain
        id: cache-musl
        uses: actions/cache@v2
        with:
          path: musl-data
          key: musl-cross-{{ runner.os }}-{{ hashFiles('dep-github-release') }}
      - name: Install Requirements
        run: |
          sudo apt update
          sudo snap install goreleaser --classic
          make dep-github-release
      - name: Releasing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make github-release

  darwin:
    needs: linux
    runs-on: macos-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - name: Install Requirements
        run: |
          brew install goreleaser
          brew install jq
          brew install wget
      - name: Releasing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make github-release-darwin
          make mac-installer-release

  windows:
    needs: darwin
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - name: Cache musl cross-compilation toolchain
        id: cache-musl
        uses: actions/cache@v2
        with:
          path: musl-data
          key: musl-cross-{{ runner.os }}-{{ hashFiles('dep-github-release') }}
      - name: Install Requirements
        shell: pwsh
        run: |
          Invoke-WebRequest "https://github.com/goreleaser/goreleaser/releases/download/v1.8.3/goreleaser_Windows_x86_64.zip" -o goreleaser.zip
          Expand-Archive goreleaser.zip
          choco install make
      - name: Releasing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make github-release-windows
          make windows-installer-release
